import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { designPalettes, paletteColors } from "../src/palettes.js";

const root = resolve(import.meta.dir, "..");
const property = (key: string) => key.replace(/[A-Z]/gu, (letter) => `-${letter.toLowerCase()}`);
const identifier = (palette: string, mode: string) => `${palette.replace(/-([a-z])/gu, (_, letter: string) => letter.toUpperCase())}${mode === "light" ? "Light" : "Dark"}`;
const declarations = (colors: Readonly<Record<string, string>>) => Object.entries(colors)
  .map(([key, value]) => `  "--hraness-palette-${property(key)}": ${JSON.stringify(value)},`).join("\n");
const source = [
  '// Generated by scripts/generate-palettes.ts from src/palettes.ts. Do not edit.',
  'import * as stylex from "@stylexjs/stylex";',
  '',
  'export const paletteTokens = stylex.defineVars({',
  declarations(paletteColors.catppuccin.dark),
  '});',
  ...designPalettes.flatMap((palette) => (["light", "dark"] as const).flatMap((mode) => [
    '', `export const ${identifier(palette, mode)} = stylex.createTheme(paletteTokens, {`,
    declarations(paletteColors[palette][mode]), '});',
  ])),
  '',
].join("\n");

const path = resolve(root, "src/palette-tokens.stylex.ts");
if (process.argv.includes("--write")) {
  await writeFile(path, source);
  console.log("Generated the eight complete StyleX palette recipes.");
} else if (await readFile(path, "utf8") !== source) {
  throw new Error("StyleX palettes are stale. Run bun run scripts/generate-palettes.ts --write.");
}
