import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const repository = resolve(import.meta.dir, "..");
const fontDirectory = join(repository, "src", "fonts", "nebula-sans");
const outputPath = join(fontDirectory, "social-fonts.generated.ts");

function wrappedBase64(bytes: Uint8Array): string {
  const encoded = Buffer.from(bytes).toString("base64");
  const chunks = encoded.match(/.{1,100}/gu) ?? [];
  return `[
${chunks.map((chunk) => `  "${chunk}",`).join("\n")}
].join("")`;
}

const [book, bold] = await Promise.all([
  readFile(join(fontDirectory, "NebulaSans-Book.otf")),
  readFile(join(fontDirectory, "NebulaSans-Bold.otf")),
]);

const source = `/* Generated by scripts/generate-nebula-social-fonts.ts. Do not edit. */

export type NebulaSansSocialFont = Readonly<{
  data: ArrayBuffer;
  name: "Nebula Sans";
  style: "normal";
  weight: 400 | 700;
}>;

const BOOK_BASE64 = ${wrappedBase64(book)};
const BOLD_BASE64 = ${wrappedBase64(bold)};
const BASE64_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

let cachedFonts: readonly NebulaSansSocialFont[] | undefined;

function decodeBase64(value: string): ArrayBuffer {
  if (value.length % 4 !== 0) throw new Error("Invalid base64 font payload length.");
  const padding = value.endsWith("==") ? 2 : value.endsWith("=") ? 1 : 0;
  const bytes = new Uint8Array((value.length / 4) * 3 - padding);
  let outputIndex = 0;

  const sextet = (character: string): number => {
    const index = BASE64_ALPHABET.indexOf(character);
    if (index < 0) throw new Error("Invalid base64 font payload character.");
    return index;
  };

  for (let index = 0; index < value.length; index += 4) {
    const third = value.charAt(index + 2);
    const fourth = value.charAt(index + 3);
    const chunk = (sextet(value.charAt(index)) << 18)
      | (sextet(value.charAt(index + 1)) << 12)
      | ((third === "=" ? 0 : sextet(third)) << 6)
      | (fourth === "=" ? 0 : sextet(fourth));
    bytes[outputIndex] = chunk >>> 16;
    outputIndex += 1;
    if (outputIndex < bytes.length) {
      bytes[outputIndex] = (chunk >>> 8) & 0xff;
      outputIndex += 1;
    }
    if (outputIndex < bytes.length) {
      bytes[outputIndex] = chunk & 0xff;
      outputIndex += 1;
    }
  }
  return bytes.buffer;
}

/** Deterministic OTF payloads for ImageResponse and other generated artwork. */
export function nebulaSansSocialFonts(): readonly NebulaSansSocialFont[] {
  cachedFonts ??= [
    {
      data: decodeBase64(BOOK_BASE64),
      name: "Nebula Sans",
      style: "normal",
      weight: 400,
    },
    {
      data: decodeBase64(BOLD_BASE64),
      name: "Nebula Sans",
      style: "normal",
      weight: 700,
    },
  ];
  return cachedFonts;
}
`;

await writeFile(outputPath, source);
