import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const repository = resolve(import.meta.dir, "..");
const fontDirectory = join(repository, "src", "fonts", "nebula-sans");
const outputPath = join(fontDirectory, "social-fonts.generated.ts");

function wrappedBase64(bytes: Uint8Array): string {
  const encoded = Buffer.from(bytes).toString("base64");
  const chunks = encoded.match(/.{1,100}/gu) ?? [];
  return `[
${chunks.map((chunk) => `  "${chunk}",`).join("\n")}
].join("")`;
}

const [book, bold] = await Promise.all([
  readFile(join(fontDirectory, "NebulaSans-Book.otf")),
  readFile(join(fontDirectory, "NebulaSans-Bold.otf")),
]);

const source = `/* Generated by scripts/generate-nebula-social-fonts.ts. Do not edit. */

export type NebulaSansSocialFont = Readonly<{
  data: ArrayBuffer;
  name: "Nebula Sans";
  style: "normal";
  weight: 400 | 700;
}>;

const BOOK_BASE64 = ${wrappedBase64(book)};
const BOLD_BASE64 = ${wrappedBase64(bold)};

let cachedFonts: readonly NebulaSansSocialFont[] | undefined;

function decodeBase64(value: string): ArrayBuffer {
  const binary = globalThis.atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes.buffer;
}

/** Deterministic OTF payloads for ImageResponse and other generated artwork. */
export function nebulaSansSocialFonts(): readonly NebulaSansSocialFont[] {
  cachedFonts ??= [
    {
      data: decodeBase64(BOOK_BASE64),
      name: "Nebula Sans",
      style: "normal",
      weight: 400,
    },
    {
      data: decodeBase64(BOLD_BASE64),
      name: "Nebula Sans",
      style: "normal",
      weight: 700,
    },
  ];
  return cachedFonts;
}
`;

await writeFile(outputPath, source);
