import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const repository = resolve(import.meta.dir, "..");
const vendorDirectory = join(repository, "vendor", "provider-marks");
const outputPath = join(repository, "src", "provider-marks.generated.ts");

interface MarkSource {
  /** Mono-capable artwork source; fills are rewritten to currentColor. */
  readonly glyph: string;
  /** Optional full-color artwork kept verbatim. */
  readonly art?: string;
}

/**
 * Vendored file per mark id. `glyph` files are recolored to currentColor so
 * surfaces retint them; `art` files keep vendor fills. Marks without a Lobe
 * glyph (Aider, Crush) reuse their art file as the glyph source.
 */
const MARK_SOURCES = {
  aider: { glyph: "aider.svg", art: "aider.svg" },
  alibabacloud: { glyph: "lobehub/alibabacloud.svg", art: "lobehub/alibabacloud-color.svg" },
  amp: { glyph: "lobehub/amp.svg", art: "lobehub/amp-color.svg" },
  anthropic: { glyph: "lobehub/anthropic.svg" },
  claude: { glyph: "lobehub/claude.svg", art: "lobehub/claude-color.svg" },
  claudecode: { glyph: "lobehub/claudecode.svg", art: "lobehub/claudecode-color.svg" },
  codex: { glyph: "lobehub/codex.svg", art: "lobehub/codex-color.svg" },
  crush: { glyph: "crush-heartbit.svg", art: "crush-heartbit.svg" },
  cursor: { glyph: "lobehub/cursor.svg" },
  deepseek: { glyph: "lobehub/deepseek.svg", art: "lobehub/deepseek-color.svg" },
  devin: { glyph: "lobehub/devin.svg", art: "lobehub/devin-color.svg" },
  gemini: { glyph: "lobehub/gemini.svg", art: "lobehub/gemini-color.svg" },
  geminicli: { glyph: "lobehub/geminicli.svg", art: "lobehub/geminicli-color.svg" },
  goose: { glyph: "lobehub/goose.svg" },
  meta: { glyph: "lobehub/meta.svg", art: "lobehub/meta-color.svg" },
  mistral: { glyph: "lobehub/mistral.svg", art: "lobehub/mistral-color.svg" },
  moonshot: { glyph: "lobehub/moonshot.svg" },
  nvidia: { glyph: "lobehub/nvidia.svg", art: "lobehub/nvidia-color.svg" },
  openai: { glyph: "lobehub/openai.svg" },
  opencode: { glyph: "lobehub/opencode.svg" },
  qwen: { glyph: "lobehub/qwen.svg", art: "lobehub/qwen-color.svg" },
  xai: { glyph: "lobehub/xai.svg" },
  zai: { glyph: "lobehub/zai.svg" },
} as const satisfies Record<string, MarkSource>;

export type ProviderMarkId = keyof typeof MARK_SOURCES;

const FORBIDDEN = /<script|on[a-z]+\s*=|javascript:/iu;

/** Reads one vendored SVG into a viewBox + sanitized inner body. */
async function readMark(file: string, tintable: boolean): Promise<{ viewBox: string; body: string }> {
  const raw = await readFile(join(vendorDirectory, file), "utf8");
  const viewBox = /viewBox="([^"]+)"/u.exec(raw)?.[1];
  if (viewBox === undefined) throw new Error(`${file} has no viewBox.`);
  const bodyMatch = /<svg[^>]*>(?<body>[\s\S]*)<\/svg>/u.exec(raw);
  const body = bodyMatch?.groups?.body;
  if (body === undefined || body.trim() === "") throw new Error(`${file} has no artwork.`);
  let normalized = body
    .replaceAll(/<title>[\s\S]*?<\/title>/gu, "")
    .replaceAll(/<defs>[\s\S]*?<\/defs>/gu, (defs) => (defs.includes("</style>") ? "" : defs))
    .replaceAll(/\s(data-name|class|style)="[^"]*"/gu, "")
    .replaceAll(/<\?xml[^?]*\?>/gu, "")
    .replaceAll(/\s+/gu, " ")
    .trim();
  if (tintable) normalized = normalized.replaceAll(/fill="(?!none)[^"]*"/gu, 'fill="currentColor"');
  if (FORBIDDEN.test(normalized)) throw new Error(`${file} contains forbidden markup.`);
  return { viewBox, body: normalized };
}

/** Emits the generated registry payload; used by both write and check mode. */
export async function providerMarksModule(): Promise<string> {
  const vendored = await readdir(vendorDirectory, { recursive: true });
  const entries: string[] = [];
  const sources = Object.entries(MARK_SOURCES) as [ProviderMarkId, MarkSource][];
  for (const [id, source] of sources.sort(([a], [b]) => a.localeCompare(b))) {
    if (!vendored.includes(source.glyph)) throw new Error(`Missing vendored glyph for ${id}: ${source.glyph}`);
    const glyph = await readMark(source.glyph, true);
    let art: { viewBox: string; body: string } | null = null;
    if (source.art !== undefined && source.art !== source.glyph) {
      if (!vendored.includes(source.art)) throw new Error(`Missing vendored art for ${id}: ${source.art}`);
      art = await readMark(source.art, false);
    }
    const artField = art === null ? "null" : `{ viewBox: ${JSON.stringify(art.viewBox)}, body: ${JSON.stringify(art.body)} }`;
    entries.push(`  ${JSON.stringify(id)}: {\n    glyph: { viewBox: ${JSON.stringify(glyph.viewBox)}, body: ${JSON.stringify(glyph.body)} },\n    art: ${artField},\n  },`);
  }
  return `/* Generated by scripts/generate-provider-marks.ts. Do not edit. */

export interface ProviderMarkArtwork {
  readonly viewBox: string;
  readonly body: string;
}

export interface ProviderMarkAssets {
  /** Monochrome artwork; every fill resolves to currentColor. */
  readonly glyph: ProviderMarkArtwork;
  /** Vendor-colored artwork when the source publishes one. */
  readonly art: ProviderMarkArtwork | null;
}

export const providerMarkAssets = {
${entries.join("\n")}
} as const satisfies Record<string, ProviderMarkAssets>;
`;
}

const source = await providerMarksModule();
if (process.argv.includes("--write")) {
  await writeFile(outputPath, source);
} else if ((await readFile(outputPath, "utf8").catch(() => "")) !== source) {
  throw new Error("Provider marks are stale. Run bun run generate:provider-marks.");
}
