import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { designPalettes, paletteColors } from "../src/palettes.js";

const root = resolve(import.meta.dir, "..");
const property = (key: string) => key.replace(/[A-Z]/gu, (letter) => `-${letter.toLowerCase()}`);
const identifier = (palette: string, mode: string) => `${palette.replace(/-([a-z])/gu, (_, letter: string) => letter.toUpperCase())}${mode === "light" ? "Light" : "Dark"}`;
const declarations = (colors: Readonly<Record<string, string>>) => Object.entries(colors)
  .map(([key, value]) => `  "--hraness-palette-${property(key)}": ${JSON.stringify(value)},`).join("\n");
const source = [
  '// Generated by scripts/generate-palettes.ts from src/palettes.ts. Do not edit.',
  'import * as stylex from "@stylexjs/stylex";',
  '',
  'export const paletteTokens = stylex.defineVars({',
  declarations(paletteColors.catppuccin.dark),
  '});',
  ...designPalettes.flatMap((palette) => (["light", "dark"] as const).flatMap((mode) => [
    '', `export const ${identifier(palette, mode)} = stylex.createTheme(paletteTokens, {`,
    declarations(paletteColors[palette][mode]), '});',
  ])),
  '',
].join("\n");

const path = resolve(root, "src/palette-tokens.stylex.ts");
// A selected family must paint before JavaScript (and when it is disabled).
// Concrete saved selections continue to use the immutable StyleX recipes.
const systemSource = [
  '/* Generated by scripts/generate-palettes.ts. System-first palette paint without JavaScript. */',
  ...designPalettes.flatMap((palette) => [
    `:root[data-palette="${palette}"]:not([data-theme]),`,
    `[data-palette="${palette}"]:not([data-theme]) {`,
    '  color-scheme: light dark;',
    ...Object.keys(paletteColors[palette].light).map((key) => {
      const role = key as keyof typeof paletteColors[typeof palette]["light"];
      return `  --hraness-palette-${property(key)}: light-dark(${paletteColors[palette].light[role]}, ${paletteColors[palette].dark[role]});`;
    }),
    '}',
    ...(["light", "dark"] as const).flatMap((mode) => [
      `:root[data-palette="${palette}"][data-theme="${mode}"],`,
      `[data-palette="${palette}"][data-theme="${mode}"] {`,
      `  color-scheme: ${mode};`,
      ...Object.entries(paletteColors[palette][mode]).map(([key, value]) => `  --hraness-palette-${property(key)}: ${value};`),
      '}',
    ]),
  ]),
  '',
].join("\n");
const systemPath = resolve(root, "src/palette-system.css");
if (process.argv.includes("--write")) {
  await writeFile(path, source);
  await writeFile(systemPath, systemSource);
  console.log(`Generated ${designPalettes.length * 2} complete StyleX palette recipes.`);
} else if (await readFile(path, "utf8") !== source) {
  throw new Error("StyleX palettes are stale. Run bun run scripts/generate-palettes.ts --write.");
}
if (!process.argv.includes("--write") && await readFile(systemPath, "utf8") !== systemSource) {
  throw new Error("System palettes are stale. Run bun run scripts/generate-palettes.ts --write.");
}
