import { readFileSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { paletteColors } from "../src/palettes.js";

// The portable snapshot carries the same paint and accessibility contract as
// current components, without importing their layout or requiring an upgrade.
const marketingCss = readFileSync(new URL("../src/product-marketing.css", import.meta.url), "utf8");
const paintParts = marketingCss.split(/\/\* marketing-header-paint:(?:start|end) \*\//u);
if (paintParts.length !== 3 || paintParts[1] === undefined) throw new Error("Expected one shared marketing header paint contract.");
const paperHeaderPaint = paintParts[1].trim().replaceAll(".hraness-marketing-header", ':where([data-hraness-theme="paper"]) .hraness-marketing-header, .hraness-marketing-header:where([data-hraness-theme="paper"])');

const property = (key: string) => key.replace(/[A-Z]/gu, (letter) => `-${letter.toLowerCase()}`);
const boundary = '[data-hraness-theme="paper"]';
const colorBoundary = `${boundary}:where(:not([data-palette]), [data-palette="paper"])`;
// Match legacy :root[data-theme] specificity only at the document boundary.
// Named palette bridges retain their higher priority and saved selections.
const colors = `:root${colorBoundary},\n${colorBoundary}`;
const declarations = Object.entries(paletteColors.paper.light).map(([key, value]) =>
  `  --${property(key)}: light-dark(${value}, ${paletteColors.paper.dark[key as keyof typeof paletteColors.paper.dark]});`);
const aliases: Readonly<Record<string, string>> = {
  "ui-background": "background", "ui-foreground": "foreground", "ui-card": "card", "ui-card-foreground": "card-foreground",
  "ui-popover": "popover", "ui-popover-foreground": "popover-foreground", "ui-primary": "primary", "ui-primary-foreground": "primary-foreground",
  "ui-secondary": "secondary", "ui-secondary-foreground": "secondary-foreground", "ui-muted": "secondary", "ui-muted-foreground": "muted",
  "ui-accent": "accent", "ui-accent-foreground": "accent-foreground", "ui-destructive": "danger", "ui-destructive-foreground": "danger-foreground",
  "ui-destructive-soft": "danger-soft", "ui-border": "line", "ui-input": "control-border", "ui-ring": "focus",
  "ui-success": "success", "ui-success-foreground": "success-foreground", "ui-success-soft": "success-soft",
  "ui-warning": "warning", "ui-warning-foreground": "warning-foreground", "ui-warning-soft": "warning-soft",
  "ui-info": "info", "ui-info-foreground": "info-foreground", "ui-info-soft": "info-soft",
  "ui-chart-1": "chart1", "ui-chart-2": "chart2", "ui-chart-3": "chart3", "ui-chart-4": "chart4", "ui-chart-5": "chart5",
  "hraness-site-accent": "primary", "hraness-site-accent-ink": "primary-foreground",
  "plain-background": "background", "plain-foreground": "foreground", "plain-muted": "muted", "plain-line": "grid", "plain-surface": "secondary", "plain-link": "primary",
  "plain-syntax-keyword": "warning", "plain-syntax-string": "success", "plain-syntax-number": "danger", "plain-syntax-name": "info",
};

export const paperThemeCss = `/* @hraness/design-kit paper-theme.css, portable contract 1.
 * Generated by scripts/generate-paper-theme.ts from src/palettes.ts.
 * Opt in with data-hraness-theme="paper". Import after existing theme rules.
 * No imports, asset requests, resets, layout recipes, or runtime dependencies.
 * Appearance uses inherited color-scheme; set data-theme on the boundary for
 * an explicit island. A root without a mode follows the operating system.
 * A non-paper data-palette on the boundary retains its selected colors.
 * Requires CSS light-dark() (Chrome 123+, Firefox 120+, Safari 17.5+).
 */

${boundary} {
  --font-text: "Nebula Sans", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --font-heading: var(--font-text);
  --font-sans: var(--font-text);
  --font-mono: ui-monospace, "SFMono-Regular", Menlo, Monaco, Consolas, monospace;
  --ui-font-sans: var(--font-text);
  --ui-font-heading: var(--font-heading);
  --ui-font-mono: var(--font-mono);
  --text-body: 1rem;
  --text-caption: .75rem;
  --text-label: .875rem;
  --font-weight-regular: 400;
  --font-weight-medium: 550;
  --font-weight-bold: 700;
  --radius-sm: .375rem;
  --radius-md: .625rem;
  --radius-lg: .875rem;
  --ui-radius: .875rem;
  --control-radius: .625rem;
  --hraness-paper-heading-size: clamp(1.75rem, 3vw, 2.375rem);
  --hraness-paper-section-heading-size: clamp(1.25rem, 2.2vw, 1.75rem);
  --hraness-paper-summary-size: 1rem;
  --hraness-paper-heading-leading: 1.15;
  --hraness-paper-heading-tracking: -.035em;
  --hraness-marketing-measure: 80rem;
  --hraness-marketing-copy-measure: 40rem;
  --hraness-marketing-prose-measure: 68ch;
  --hraness-marketing-gutter: clamp(1.25rem, 4vw, 3rem);
  --hraness-marketing-radius: .625rem;
  --hraness-marketing-frame-radius: .875rem;
  --hraness-marketing-heading-weight: 550;
  --hraness-marketing-heading-tracking: -.025em;
  --hraness-marketing-section-space: clamp(3rem, 7vw, 6rem);
  --hraness-marketing-action-height: 2.75rem;
  font-family: var(--font-text);
}

/* Existing marketing roles declare defaults directly, so inherit this
 * opt-in rhythm at each role boundary without replacing component recipes. */
${boundary} :where(.hraness-marketing-page, .hraness-marketing-header, .hraness-marketing-hero, .hraness-marketing-pillars, .hraness-marketing-install, .hraness-marketing-section, .hraness-marketing-primitives, .hraness-marketing-stats, .hraness-marketing-interfaces, .hraness-marketing-trust, .hraness-marketing-quotes, .hraness-marketing-pricing, .hraness-marketing-questions, .hraness-marketing-maker, .hraness-marketing-cta, .hraness-marketing-proof-frame) {
  --hraness-marketing-measure: inherit;
  --hraness-marketing-copy-measure: inherit;
  --hraness-marketing-prose-measure: inherit;
  --hraness-marketing-gutter: inherit;
  --hraness-marketing-radius: inherit;
  --hraness-marketing-frame-radius: inherit;
  --hraness-marketing-heading-weight: inherit;
  --hraness-marketing-heading-tracking: inherit;
  --hraness-marketing-section-space: inherit;
  --hraness-marketing-action-height: inherit;
}

:root${boundary}:where(:not([data-theme]):not(.dark), [data-theme="system"]) { color-scheme: light dark; }
${boundary}:where([data-theme="dark"], .dark:not([data-theme="light"])) { color-scheme: dark; }
${boundary}[data-theme="light"] { color-scheme: light; }

/* Opted-in shared headers retain their layout and receive the shared paint
 * contract, including snapshots used with older component releases. */
@layer components.hraness-design-kit.legacy {
${paperHeaderPaint}
}

${colors} {
${declarations.join("\n")}
${Object.entries(aliases).map(([name, target]) => `  --${name}: var(--${target});`).join("\n")}
}

/* Standalone snapshots need their own derived light and shade. A lower-priority
 * layer supplies identical portable depth without overriding installed UI roles. */
@layer base {
${colors} {
  --ui-surface-light: color-mix(in oklch, var(--card) 94%, white);
  --ui-surface-shade: color-mix(in oklch, var(--background) 55%, black);
  --elevation-low: inset 0 1px 0 color-mix(in srgb, var(--ui-surface-light) 72%, transparent), 0 1px 2px -1px color-mix(in srgb, var(--ui-surface-shade) 20%, transparent), 0 4px 10px -6px color-mix(in srgb, var(--ui-surface-shade) 22%, transparent);
  --elevation-raised: inset 0 1px 0 color-mix(in srgb, var(--ui-surface-light) 72%, transparent), 0 2px 4px -2px color-mix(in srgb, var(--ui-surface-shade) 18%, transparent), 0 14px 28px -16px color-mix(in srgb, var(--ui-surface-shade) 30%, transparent);
  --elevation-overlay: inset 0 1px 0 color-mix(in srgb, var(--ui-surface-light) 80%, transparent), 0 4px 12px -4px color-mix(in srgb, var(--ui-surface-shade) 24%, transparent), 0 24px 64px -20px color-mix(in srgb, var(--ui-surface-shade) 38%, transparent);
  --elevation-inset: inset 0 2px 4px -2px color-mix(in srgb, var(--ui-surface-shade) 24%, transparent), inset 0 -1px 0 color-mix(in srgb, var(--ui-surface-light) 44%, transparent);
}
}

@media (forced-colors: active) {
  ${colors} {
    --background: Canvas;
    --foreground: CanvasText;
    --muted: CanvasText;
    --faint: CanvasText;
    --surface: Canvas;
    --surface-raised: Canvas;
    --surface-hover: Canvas;
    --card: Canvas;
    --card-foreground: CanvasText;
    --popover: Canvas;
    --popover-foreground: CanvasText;
    --secondary: Canvas;
    --secondary-foreground: CanvasText;
    --grid: CanvasText;
    --line: CanvasText;
    --control-border: ButtonText;
    --primary: Highlight;
    --primary-foreground: HighlightText;
    --plain-link: LinkText;
    --accent: Highlight;
    --accent-foreground: HighlightText;
    --focus: Highlight;
    --inverse: CanvasText;
    --inverse-foreground: Canvas;
    --disabled: Canvas;
    --disabled-foreground: GrayText;
    --elevation-low: none;
    --elevation-raised: none;
    --elevation-overlay: none;
    --elevation-inset: none;
  }
}
`;

if (import.meta.main) {
  const path = resolve(import.meta.dir, "../src/paper-theme.css");
  if (process.argv.includes("--write")) await writeFile(path, paperThemeCss);
  else if (await readFile(path, "utf8") !== paperThemeCss) throw new Error("Paper theme is stale. Run bun run generate:paper-theme.");
}
