import * as stylex from "@stylexjs/stylex";

export const marketingAccountStyles = stylex.create({
  section: {
    alignItems: "center",
    "border-top": "var(--hraness-marketing-rule, 1px solid var(--line))",
    color: "var(--foreground)",
    display: "grid",
    gap: "2rem 4rem",
    gridTemplateColumns: { default: "minmax(0, 1fr)", "@media (min-width: 50rem)": "minmax(0, 1fr) minmax(0, 1fr)" },
    paddingBlock: "clamp(2.5rem, 6vw, 4rem)",
    scrollMarginTop: "calc(var(--hraness-sticky-offset, 5rem) + 2rem)",
  },
  copy: { minWidth: 0 },
  heading: {
    fontFamily: "var(--font-text)",
    fontSize: "clamp(1.625rem, 1.3rem + 1vw, 2.25rem)",
    fontWeight: 550,
    letterSpacing: "-0.02em",
    lineHeight: 1.15,
    margin: 0,
    textWrap: "balance",
  },
  summary: {
    color: "var(--muted)",
    fontSize: "1rem",
    lineHeight: 1.6,
    marginTop: "1rem",
    maxWidth: "42ch",
    textWrap: "pretty",
  },
  content: { minWidth: 0 },
  actions: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "0.75rem 1.5rem" },
  primary: {
    alignItems: "center",
    backgroundColor: { default: "var(--primary)", ":hover": "color-mix(in oklch, var(--primary) 88%, var(--foreground))", "@media (forced-colors: active)": "ButtonFace" },
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "transparent", "@media (forced-colors: active)": "ButtonText" },
    borderRadius: "0.625rem",
    color: { default: "var(--primary-foreground)", "@media (forced-colors: active)": "ButtonText" },
    display: "inline-flex",
    fontFamily: "var(--font-text)",
    fontSize: "1.0625rem",
    fontWeight: 550,
    justifyContent: "center",
    lineHeight: 1.3,
    maxWidth: "100%",
    minHeight: "3.5rem",
    outline: { default: null, ":focus-visible": "2px solid var(--primary)" },
    outlineOffset: { default: null, ":focus-visible": "3px" },
    paddingBlock: "0.875rem",
    paddingInline: "1.5rem",
    textAlign: "center",
    textDecoration: "none",
  },
  signIn: {
    alignItems: "center",
    color: { default: "var(--foreground)", "@media (forced-colors: active)": "LinkText" },
    display: "inline-flex",
    fontFamily: "var(--font-text)",
    fontSize: "1.0625rem",
    fontWeight: 450,
    lineHeight: 1.3,
    minHeight: "3.5rem",
    outline: { default: null, ":focus-visible": "2px solid var(--primary)" },
    outlineOffset: { default: null, ":focus-visible": "3px" },
    textDecorationLine: "underline",
    textDecorationStyle: "dotted",
    textDecorationColor: { default: "color-mix(in srgb, currentColor 45%, transparent)", ":hover": "currentColor", ":focus-visible": "currentColor", "@media (forced-colors: active)": "LinkText" },
    textDecorationThickness: "1px",
    textUnderlineOffset: "0.22em",
  },
});
