/* Generated by scripts/generate-icons.ts. Do not edit. */

export interface HranessIconAsset {
  /** Sanitized inner SVG artwork for inline rendering. */
  readonly body: string;
  /** Presentation context the icon was generated and admitted for. */
  readonly context: "card" | "hero" | "inline";
  /** Canonical file path inside the package's `./icons/*` export. */
  readonly file: string;
  readonly ink: string;
  readonly purpose: "illustration" | "mark";
  readonly set: string;
  readonly slug: string;
  readonly subject: string;
  readonly viewBox: string;
}

export const hranessIconAssets = {

} as const satisfies Record<string, HranessIconAsset>;
