/**
 * Public Hraness portfolio facts: product names, one-liners, canonical URLs,
 * status, and the registered relations between products.
 *
 * The data is a versioned snapshot generated by `scripts/sync-portfolio-facts.ts`
 * from one exact commit of the Hraness portfolio registry, recorded in
 * `portfolioProvenance`. This
 * module holds data and pure helpers only. It renders nothing and imports no
 * other part of the package.
 */
import { portfolioSnapshot } from "./portfolio.generated.js";

export const portfolioRelationKinds = ["runtime", "development", "contract", "delivery"] as const;
export type PortfolioRelationKind = (typeof portfolioRelationKinds)[number];

/** `forward` reads source to target; `shared` is a symmetric contract both sides implement. */
export const portfolioRelationDirections = ["forward", "shared"] as const;
export type PortfolioRelationDirection = (typeof portfolioRelationDirections)[number];

/** Every product in the public portfolio contract is an active product. */
export const portfolioProductStatuses = ["active"] as const;
export type PortfolioProductStatus = (typeof portfolioProductStatuses)[number];

/** Whether the registry's structured marketing copy is reviewed (`authored`) or a draft (`proposed`). */
export const portfolioCopyStatuses = ["authored", "proposed"] as const;
export type PortfolioCopyStatus = (typeof portfolioCopyStatuses)[number];

export type PortfolioProductId = keyof typeof portfolioSnapshot.products;

/** The canonical messaging record for one product, verbatim from the public portfolio contract. */
export type PortfolioMessaging = Readonly<{
  formatVersion: 1;
  /** The canonical product slug, which can differ from the registry id. */
  product: string;
  names: Readonly<{
    /** The prose name, used inside sentences. */
    name: string;
    /** The all-caps catalog name hraness.com cards display. */
    catalog?: string;
    command?: string;
    /** Retired names that still route to the product. */
    formerly?: readonly string[];
  }>;
  /** The product class, at most four words. */
  category: string;
  tagline: string;
  /** The card line; sentence case without the product name or a final period. */
  short: string;
  /** The 110-to-160-character description for meta tags, GitHub About, and listings. */
  meta: string;
  /** Two-sentence copy that opens with the product name. */
  medium: string;
  long?: string;
  headlines?: readonly string[];
  hero?: Readonly<{
    heading?: string;
    summary?: string;
    primaryAction?: string;
    secondaryAction?: string;
  }>;
  channels?: Readonly<Record<string, unknown>>;
  /** Per-tier authorship; tiers not listed take `default`. */
  status: Readonly<{ default: PortfolioCopyStatus } & Partial<Record<string, PortfolioCopyStatus>>>;
  reviewedOn?: string;
}>;

export type PortfolioProduct = Readonly<{
  id: PortfolioProductId;
  /** The name in its canonical casing, taken from the product's brand entry when it owns its host. */
  name: string;
  /** The product's `short` line in canonical casing. */
  oneLiner: string;
  /** The brand catalog's description, or null when it has none. It can differ from `oneLiner`. */
  brandDescription: string | null;
  canonicalUrl: string;
  status: PortfolioProductStatus;
  /** Whether the registry's default copy tier is reviewed (`authored`) or a draft (`proposed`). */
  copyStatus: PortfolioCopyStatus;
  /** Other names the registry uses for the product, such as an expanded, display, or retired name. */
  aliases: readonly string[];
  /** The canonical tiered copy record: names, category, tagline, short, meta, medium, long, hero, and channels. */
  messaging: PortfolioMessaging;
}>;

export type PortfolioRelation = Readonly<{
  id: string;
  source: PortfolioProductId;
  target: PortfolioProductId;
  kind: PortfolioRelationKind;
  direction: PortfolioRelationDirection;
  /** A short registry label such as "compacts sessions for". It is not reader-facing copy. */
  label: string;
  /** One reviewed sentence describing the integration, or null when none is registered. */
  detail: string | null;
}>;

export type PortfolioProvenance = Readonly<{
  /** The public home of the upstream facts, https://hraness.com/portfolio.json. */
  registry: string;
  /** The full 40-character registry commit the snapshot was generated from. */
  commit: string;
  /** The commit's date, YYYY-MM-DD. */
  committedOn: string;
  upstreamContract: string;
  upstreamDigest: string;
  files: readonly Readonly<{ path: string; sha256: string }>[];
}>;

export type PortfolioSnapshot = Readonly<{
  contract: "hraness.design-kit-portfolio/v1";
  formatVersion: 1;
  provenance: PortfolioProvenance;
  products: Readonly<Record<PortfolioProductId, PortfolioProduct>>;
  relations: readonly PortfolioRelation[];
  /** SHA-256 of the snapshot's compact JSON without this key. Pin it in a consumer test. */
  digest: string;
}>;

/** A related-product card, shaped for `MarketingRelated` and `ArticleRelatedProducts` items. */
export type PortfolioRelatedItem = Readonly<{
  href: string;
  name: string;
  /** The related product's one-liner. */
  role: string;
  /** The relation's reviewed detail sentence. */
  relationship: string;
  productId: PortfolioProductId;
  relationId: string;
}>;

/** A product pair joined by a relation with a reviewed detail, for "How X uses Y" posts. */
export type PortfolioUsesPair = Readonly<{
  relation: PortfolioRelation & Readonly<{ detail: string }>;
  source: PortfolioProduct;
  target: PortfolioProduct;
}>;

export class PortfolioFactsError extends Error {
  override readonly name = "PortfolioFactsError";
}

function deepFreeze<T>(value: T): T {
  if (typeof value === "object" && value !== null && !Object.isFrozen(value)) {
    for (const child of Object.values(value)) deepFreeze(child);
    Object.freeze(value);
  }
  return value;
}

/** The whole snapshot, frozen so one consumer cannot change another's facts at runtime. */
export const portfolioFacts: PortfolioSnapshot = deepFreeze(portfolioSnapshot);
export const portfolioProducts: PortfolioSnapshot["products"] = portfolioFacts.products;
export const portfolioRelations: PortfolioSnapshot["relations"] = portfolioFacts.relations;
export const portfolioProvenance: PortfolioProvenance = portfolioFacts.provenance;
export const portfolioDigest: string = portfolioFacts.digest;

/** Product ids in registry order. */
export const portfolioProductIds: readonly PortfolioProductId[] = Object.freeze(
  Object.keys(portfolioProducts) as PortfolioProductId[],
);

export function isPortfolioProductId(value: unknown): value is PortfolioProductId {
  return typeof value === "string" && Object.hasOwn(portfolioProducts, value);
}

/** Returns one product, or throws `PortfolioFactsError` for an id that is not in the snapshot. */
export function product(id: PortfolioProductId): PortfolioProduct {
  if (!isPortfolioProductId(id)) {
    throw new PortfolioFactsError(`Unknown portfolio product: ${String(id)}.`);
  }
  return portfolioProducts[id];
}

function hasDetail(relation: PortfolioRelation): relation is PortfolioRelation & Readonly<{ detail: string }> {
  return relation.detail !== null;
}

/**
 * Products related to `id`, one card per related product, in relation order.
 * Only relations with a reviewed detail sentence qualify, because the card
 * shows that sentence. Pass `kinds` to narrow the relation kinds.
 */
export function relatedFor(
  id: PortfolioProductId,
  options: Readonly<{ kinds?: readonly PortfolioRelationKind[] }> = {},
): readonly PortfolioRelatedItem[] {
  product(id);
  const kinds = options.kinds ?? portfolioRelationKinds;
  const seen = new Set<PortfolioProductId>();
  const items: PortfolioRelatedItem[] = [];
  for (const relation of portfolioRelations) {
    if (!hasDetail(relation) || !kinds.includes(relation.kind)) continue;
    const otherId = relation.source === id ? relation.target : relation.target === id ? relation.source : null;
    if (otherId === null || otherId === id || seen.has(otherId)) continue;
    seen.add(otherId);
    const other = product(otherId);
    items.push({
      href: other.canonicalUrl,
      name: other.name,
      role: other.oneLiner,
      relationship: relation.detail,
      productId: other.id,
      relationId: relation.id,
    });
  }
  return items;
}

/**
 * Integration pairs with a reviewed detail sentence: the candidates for
 * "How X uses Y" posts and provider hub pages. Delivery relations (one product
 * served under another's route) are excluded. The relation does not say which
 * side is the consumer; read `detail`.
 */
export function usesPairs(): readonly PortfolioUsesPair[] {
  return portfolioRelations.filter(hasDetail).filter((relation) => relation.kind !== "delivery").map((relation) => ({
    relation,
    source: product(relation.source),
    target: product(relation.target),
  }));
}
